services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - W:/sara/VCCE:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/code_editor
      - SECRET_KEY=your_secure_secret_key_here
      - ALLOWED_ORIGINS=*
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=code_editor
    ports:
      - "5432:5432"

volumes:
  postgres_data: